- name: Create user account and set hostname
  hosts: all
  become: true
  vars_files:
    - vars/system.yml
  tasks:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
    - name: Create user account
      user:
        name: "{{ system_user_name }}"
        # We need to force ansible-vault decryption before hashing the password. (っ,-)
        password: "{{ '%s' | format(system_user_password) | password_hash('sha512') }}"
        update_password: on_create
        groups: sudo
        append: true

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/hostname_module.html
    - name: Set hostname to match inventory
      hostname:
        name: "{{ inventory_hostname }}"

- name: Deploy database
  hosts: database
  become: true
  vars_files:
    - vars/postgresql.yml
  roles:
    # https://github.com/geerlingguy/ansible-role-postgresql
    - geerlingguy.postgresql

- name: Deploy DNSRR
  hosts: webserver
  become: true
  roles:
    # https://github.com/geerlingguy/ansible-role-docker
    - geerlingguy.docker
  tasks:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
    - name: Clone Git Repository
      become: true
      git:
        repo: https://github.com/GDWR/dockercompose_dnsrr_loadbalancing.git
        dest: /opt/dnsrr

    # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_v2_module.html
    - name: Bring up docker compose
      become: true
      community.docker.docker_compose_v2:
        project_src: /opt/dnsrr

